name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Prepare environment
      run: sudo ./.github/ci-dependencies.sh

    - name: Install dependencies
      run: make deps

    - name: Lint
      run: make lint

    - name: Benchmark
      run: make benchmark
