name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.2.796'

    - name: Prepare environment
      run: sudo apt-get install -y gnuplot python3-setuptools rlwrap

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache
      env:
        cache-name: dependencies
      with:
        path: |
          /tmp/dependencies
          /usr/lib/python3/dist-packages
          node_modules
        key: ${{ runner.os }}-local-${{ env.cache-name }}-${{ hashFiles('DEPENDENCIES') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('package.json') }}

    - name: Install dependencies
      run: make deps DEPSDIR=/tmp/dependencies
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Lint
      run: make lint

    - name: Benchmark
      run: make benchmark DEPSDIR=/tmp/dependencies
